version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder-web
    volumes:
      - ./apps/web:/app/apps/web
    ports:
      - '3001:3001'
    command: npm run dev

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - ./apps/api:/app/apps/api
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
      DATABASE_URL: postgres://postgres:postgres@db:5432/mydb
    ports:
      - '3000:3000'
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'

volumes:
  postgres-data:

